# Generated by Django 5.2.5 on 2025-10-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_opened_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_opened_note',
        ),
    ]
